In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
cus = pd.read_excel("../dataset/Ecomm.xlsx",sheet_name="CustomerDetail"  )

In [3]:
cus.shape

(24, 12)

In [4]:
cus.head(2)

,CustomerID,CustomerID.1,Order Date,Month,MonthName,DateInText,Customer Name,State or Province,City,Gender,Gender.1,Gender.2
0,CUS7253,7253,2015-01-07,1,Jan,01/07/2015,Bonnie Potter,Washington,Anacortes,M,1,MALE
1,CUS4875,4875,2015-06-13,6,Jun,06/13/2015,Ronnie Proctor,California,San Gabriel,F,0,FEMALE

In [5]:
order = pd.read_excel("../dataset/Ecomm.xlsx", sheet_name='Jan')

In [6]:
order.shape

(1952, 8)

In [7]:
order.head(2)

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [8]:
cus.isnull().sum()

CustomerID           0
CustomerID.1         0
Order Date           0
Month                0
MonthName            0
DateInText           0
Customer Name        0
State or Province    0
City                 0
Gender               0
Gender.1             0
Gender.2             0
dtype: int64

In [9]:
cus = cus.drop(columns=['CustomerID','DateInText','Month','MonthName','Gender','Gender.1'])

In [10]:
cus.head(2)

,CustomerID.1,Order Date,Customer Name,State or Province,City,Gender.2
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE

In [11]:
cus = cus.rename(columns={'CustomerID.1':'CustomerID','Gender.2':'Gender'})

In [12]:
cus.head(2)

,CustomerID,Order Date,Customer Name,State or Province,City,Gender
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE

In [13]:
order.head(2)

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [14]:
order.isnull().sum()

Order ID                0
CustomerID              0
Amount                  0
Profit                  0
Quantity ordered new    0
Product Category        0
Product Sub-Category    0
Payment Mode            0
dtype: int64

In [15]:
cus.duplicated().sum()

np.int64(0)

In [16]:
cus = cus.drop_duplicates()

In [17]:
order.duplicated().sum()

np.int64(0)

In [18]:
order = order.drop_duplicates()

In [20]:
cus.head(2)

,CustomerID,Order Date,Customer Name,State or Province,City,Gender
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE

In [21]:
cus.info()

<class 'pandas.DataFrame'>
RangeIndex: 24 entries, 0 to 23
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         24 non-null     int64
 1   Order Date         24 non-null     datetime64[us]
 2   Customer Name      24 non-null     str
 3   State or Province  24 non-null     str
 4   City               24 non-null     str
 5   Gender             24 non-null     str
dtypes: datetime64[us](1), int64(1), str(4)
memory usage: 2.1 KB

In [ ]:
cus.iloc[0].reset_index()   # index wise data nikalne ke liye index ko lock krna padtha hai
# reset_index data ko dataframe me convert krta hai

               index                    0
0         CustomerID                 7253
1         Order Date  2015-01-07 00:00:00
2      Customer Name        Bonnie Potter
3  State or Province           Washington
4               City            Anacortes
5             Gender                 MALE

In [27]:
list(cus.iloc[0].reset_index()[0])

[np.int64(7253),
 Timestamp('2015-01-07 00:00:00'),
 'Bonnie Potter',
 'Washington',
 'Anacortes',
 'MALE']

In [ ]:
int(list(cus.iloc[0].reset_index()[0])[0])

7253

In [36]:
for val in list(cus.iloc[0].reset_index()[0]):
    print(val)

7253
2015-01-07 00:00:00
Bonnie Potter
Washington
Anacortes
MALE

In [ ]:
val = list(cus.iloc[0].reset_index()[0])
data = [int(val[0]), str(val[1]), val[2], val[3], val[4], val[5]]
sql = 'insert into customer values(%s,%s,%s,%s,%s,%s)'
cur.execute(sql,data)

7253
2015-01-07 00:00:00
Bonnie Potter
Washington
Anacortes
MALE

In [41]:
order.head(2)

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [40]:
list(order.iloc[0].reset_index()[0])

[np.int64(88522),
 np.int64(4666),
 np.float64(11.36),
 np.float64(4.56),
 np.int64(4),
 'Office Supplies',
 'Pens & Art Supplies',
 'Credit Card']

In [ ]:
val = list(order.iloc[0].reset_index()[0])
data = [int(val[0]),int(val[1]),float(val[2]),float(val[3]),float(val[4]),val[5],val[6],val[7]]
sql = 'insert into orders value(%s,%s,%s,%s,%s,%s,%s,%s)'
cur.execute(sql,data)